//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMenu
    {
        public int PageId { get; set; }
        public Nullable<int> ParentPageId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string PageUrl { get; set; }
        public string PageTitle { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> SuperAdmin { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<bool> Technician { get; set; }
        public Nullable<bool> Accountant { get; set; }
        public Nullable<bool> Editor { get; set; }
        public Nullable<bool> Ticketing { get; set; }
    }
}
