//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public int Id { get; set; }
        public string AirlineCode { get; set; }
        public string AirlineCodeICAO { get; set; }
        public string AirlineName { get; set; }
        public string CountryCode { get; set; }
        public string Website { get; set; }
        public Nullable<bool> IsAutoSuggest { get; set; }
    }
}
