//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public int Id { get; set; }
        public string AirportCode { get; set; }
        public string CityCode { get; set; }
        public string CityName { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> CountryPriority { get; set; }
        public string StateCode { get; set; }
        public string AirportNameEN { get; set; }
        public string AirportNameVN { get; set; }
        public string SuggestNormal { get; set; }
        public string SuggestNormalVN { get; set; }
        public string SuggestMobile { get; set; }
        public Nullable<bool> IsAutoSuggest { get; set; }
        public Nullable<bool> IsMainAirport { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> OrderDisplay { get; set; }
    }
}
