//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int Id { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> CountryDisplayOrder { get; set; }
        public string CityCode { get; set; }
        public string Name { get; set; }
        public string NameVN { get; set; }
        public Nullable<bool> IsAutoSuggest { get; set; }
        public Nullable<bool> IsMainCity { get; set; }
        public Nullable<bool> IsBigCity { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
