//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameVN { get; set; }
        public Nullable<bool> AllowsBilling { get; set; }
        public Nullable<bool> AllowsShipping { get; set; }
        public string TwoLetterIsoCode { get; set; }
        public string ThreeLetterIsoCode { get; set; }
        public Nullable<int> NumericIsoCode { get; set; }
        public string ContinentCode { get; set; }
        public Nullable<bool> SubjectToVat { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
