//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReview
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Vocative { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string City { get; set; }
        public string Review { get; set; }
        public Nullable<System.DateTime> DateTimeInsert { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string Answer { get; set; }
        public string UserAnswer { get; set; }
        public string MobileUserAnswer { get; set; }
        public Nullable<bool> ActiveAnswer { get; set; }
        public Nullable<System.DateTime> DateTimeAnswer { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> ShowOnHomepage { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IpAddress { get; set; }
    }
}
