//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFeedback
    {
        public int Id { get; set; }
        public string PassengerName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> DateQuestion { get; set; }
        public Nullable<System.DateTime> DateAnswer { get; set; }
        public Nullable<int> UserIdAnswer { get; set; }
        public Nullable<bool> IsAnswer { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> SessionId { get; set; }
    }
}
