//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequest
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<System.DateTime> DateTimeInsert { get; set; }
        public Nullable<int> UserProcess { get; set; }
        public Nullable<byte> RequestType { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Note { get; set; }
    }
}
