//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomesticFee
    {
        public int Id { get; set; }
        public string AirlineCode { get; set; }
        public string AirportCode { get; set; }
        public string AirportCodeArrival { get; set; }
        public string TicketClass { get; set; }
        public Nullable<decimal> AirportSurchargeAdult { get; set; }
        public Nullable<decimal> AirportSurchargeChild { get; set; }
        public Nullable<decimal> AirportSurchargeInfant { get; set; }
        public Nullable<decimal> ServiceFeeAdult { get; set; }
        public Nullable<decimal> ServiceFeeChild { get; set; }
        public Nullable<decimal> ServiceFeeInfant { get; set; }
        public Nullable<int> PercentBaseFeeChild { get; set; }
        public Nullable<int> PercentBaseFeeInfant { get; set; }
        public Nullable<byte> DomesticFeeStatus { get; set; }
    }
}
