//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomesticDiscount
    {
        public int Id { get; set; }
        public string Airline { get; set; }
        public Nullable<byte> DiscountType { get; set; }
        public Nullable<decimal> DiscountAdult { get; set; }
        public Nullable<decimal> DiscountChild { get; set; }
        public Nullable<decimal> DiscountInfant { get; set; }
        public Nullable<decimal> IndividualAdult { get; set; }
        public Nullable<decimal> IndividualChild { get; set; }
        public Nullable<decimal> IndividualInfant { get; set; }
    }
}
