//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareName
    {
        public int Id { get; set; }
        public string AirlineCode { get; set; }
        public string TicketClass { get; set; }
        public string FareTypeEN { get; set; }
        public string FareTypeVN { get; set; }
    }
}
