//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareRuleVNA
    {
        public int Id { get; set; }
        public Nullable<int> FareNameId { get; set; }
        public string FlightChange { get; set; }
        public string ItineraryChange { get; set; }
        public string CancellationAndRefund { get; set; }
        public string MaximumStay { get; set; }
        public string MinimumStay { get; set; }
        public string GLPAccuralRates { get; set; }
        public Nullable<int> MarketId { get; set; }
    }
}
