//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareRule
    {
        public int Id { get; set; }
        public string AirlineCode { get; set; }
        public string TicketClass { get; set; }
        public Nullable<byte> RuleName { get; set; }
        public string RuleDetail { get; set; }
        public string RuleSimple { get; set; }
    }
}
