//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandingPage
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string MetaDescription { get; set; }
        public string Metakeyword { get; set; }
        public string Summary { get; set; }
        public string Content { get; set; }
        public string ImageUrl { get; set; }
        public string AirportCode { get; set; }
        public string AirportCode1 { get; set; }
        public string Code { get; set; }
        public Nullable<int> CodeType { get; set; }
        public Nullable<bool> AllowComment { get; set; }
        public Nullable<bool> ShowInHomePage { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
