//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localization
    {
        public int Id { get; set; }
        public Nullable<byte> NameType { get; set; }
        public string RelateCode { get; set; }
        public string LangCountryCode { get; set; }
        public string Name { get; set; }
    }
}
