//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkupAndDiscount
    {
        public int Id { get; set; }
        public Nullable<byte> RecordType { get; set; }
        public string AirlineCode { get; set; }
        public Nullable<int> ValueOneWay { get; set; }
        public Nullable<int> ValueRoundTrip { get; set; }
        public Nullable<byte> ValueType { get; set; }
        public Nullable<byte> BaseOnType { get; set; }
        public string Note { get; set; }
        public string ThirdParty { get; set; }
    }
}
