//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkytourWebEntities2 : DbContext
    {
        public SkytourWebEntities2()
            : base("name=SkytourWebEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminMenu> AdminMenus { get; set; }
        public virtual DbSet<Airline> Airlines { get; set; }
        public virtual DbSet<AirlineTopupBalance> AirlineTopupBalances { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<ARCNameRule> ARCNameRules { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ConfigCategory> ConfigCategories { get; set; }
        public virtual DbSet<ConfigValue> ConfigValues { get; set; }
        public virtual DbSet<ConfigValueOption> ConfigValueOptions { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CreditCardFee> CreditCardFees { get; set; }
        public virtual DbSet<CustomerFeedback> CustomerFeedbacks { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<CustomerRequest> CustomerRequests { get; set; }
        public virtual DbSet<CustomerReview> CustomerReviews { get; set; }
        public virtual DbSet<DomesticDiscount> DomesticDiscounts { get; set; }
        public virtual DbSet<DomesticFee> DomesticFees { get; set; }
        public virtual DbSet<DomesticRoute> DomesticRoutes { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<FareName> FareNames { get; set; }
        public virtual DbSet<FareRule> FareRules { get; set; }
        public virtual DbSet<FareRuleVNA> FareRuleVNAs { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Hotline> Hotlines { get; set; }
        public virtual DbSet<HotlineBusy> HotlineBusies { get; set; }
        public virtual DbSet<HTMLBlock> HTMLBlocks { get; set; }
        public virtual DbSet<LandingPage> LandingPages { get; set; }
        public virtual DbSet<Localization> Localizations { get; set; }
        public virtual DbSet<MarkupAndDiscount> MarkupAndDiscounts { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsLetterSubscription> NewsLetterSubscriptions { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<OrderBaggage> OrderBaggages { get; set; }
        public virtual DbSet<OrderBlockFlight> OrderBlockFlights { get; set; }
        public virtual DbSet<OrderBooking> OrderBookings { get; set; }
        public virtual DbSet<OrderContactInfo> OrderContactInfoes { get; set; }
        public virtual DbSet<OrderCustomerAddress> OrderCustomerAddresses { get; set; }
        public virtual DbSet<OrderEmail> OrderEmails { get; set; }
        public virtual DbSet<OrderFlight> OrderFlights { get; set; }
        public virtual DbSet<OrderFlightSegment> OrderFlightSegments { get; set; }
        public virtual DbSet<OrderHotel> OrderHotels { get; set; }
        public virtual DbSet<OrderHotelRoom> OrderHotelRooms { get; set; }
        public virtual DbSet<OrderPayment> OrderPayments { get; set; }
        public virtual DbSet<OrderPaymentBaoKim> OrderPaymentBaoKims { get; set; }
        public virtual DbSet<OrderPaymentNganLuong> OrderPaymentNganLuongs { get; set; }
        public virtual DbSet<OrderPaymentSoHa> OrderPaymentSoHas { get; set; }
        public virtual DbSet<OrderReceipt> OrderReceipts { get; set; }
        public virtual DbSet<OrderRecheck> OrderRechecks { get; set; }
        public virtual DbSet<OrderRemark> OrderRemarks { get; set; }
        public virtual DbSet<OrderTour> OrderTours { get; set; }
        public virtual DbSet<OrderTransaction> OrderTransactions { get; set; }
        public virtual DbSet<OrderTraveller> OrderTravellers { get; set; }
        public virtual DbSet<PriceBaggage> PriceBaggages { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<SearchInput> SearchInputs { get; set; }
        public virtual DbSet<SearchSession> SearchSessions { get; set; }
        public virtual DbSet<SearchW> SearchWS { get; set; }
        public virtual DbSet<SearchWSHistory> SearchWSHistories { get; set; }
        public virtual DbSet<ServiceFee> ServiceFees { get; set; }
        public virtual DbSet<SMSBank> SMSBanks { get; set; }
        public virtual DbSet<TargetMarket> TargetMarkets { get; set; }
        public virtual DbSet<TickitBlockFlight> TickitBlockFlights { get; set; }
        public virtual DbSet<TourCategory> TourCategories { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<TurnoverWage> TurnoverWages { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserStaff> UserStaffs { get; set; }
        public virtual DbSet<VNFareClass> VNFareClasses { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<District> Districts { get; set; }
    }
}
