//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int Id { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string CityCode { get; set; }
        public string Email { get; set; }
        public string Hotline { get; set; }
        public Nullable<bool> IsAgencys { get; set; }
        public Nullable<decimal> FeeAgecys { get; set; }
        public string MapImageUrl { get; set; }
        public Nullable<decimal> ServiceAgencys { get; set; }
    }
}
