//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPaymentNganLuong
    {
        public int Id { get; set; }
        public string Order_Id { get; set; }
        public string Payment_Id { get; set; }
        public string Transaction_Info { get; set; }
        public string Amount { get; set; }
        public string Transaction_Type { get; set; }
        public string Payment_Type { get; set; }
        public string Payer_FullName { get; set; }
        public string Payer_Email { get; set; }
        public string Payer_Mobile { get; set; }
        public string Delivery_Address { get; set; }
        public Nullable<System.DateTime> Created_Time { get; set; }
        public Nullable<System.DateTime> Paid_Time { get; set; }
        public string Transaction_Status { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public string Response_Order_Id { get; set; }
        public Nullable<System.DateTime> ResponseDateTime { get; set; }
    }
}
