//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPaymentBaoKim
    {
        public int Id { get; set; }
        public string order_id { get; set; }
        public string transaction_id { get; set; }
        public string created_on { get; set; }
        public string payment_type { get; set; }
        public string transaction_status { get; set; }
        public string total_amount { get; set; }
        public string net_amount { get; set; }
        public string fee_amount { get; set; }
        public string merchant_id { get; set; }
        public string customer_name { get; set; }
        public string customer_email { get; set; }
        public string customer_phone { get; set; }
        public string customer_address { get; set; }
        public string verify_sign { get; set; }
        public string resend { get; set; }
        public Nullable<System.DateTime> DateTimeInsert { get; set; }
        public string strResponse { get; set; }
        public string order_id_response { get; set; }
        public string transaction_id_response { get; set; }
        public string transaction_status_response { get; set; }
        public string order_description_response { get; set; }
        public Nullable<System.DateTime> DatetimeResponse { get; set; }
    }
}
