//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTraveller
    {
        public int Id { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<byte> UserRole { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderFlightId { get; set; }
        public Nullable<int> OrderPackageHotelRoomId { get; set; }
        public Nullable<int> OrderHotelRoomId { get; set; }
        public Nullable<byte> TravellerType { get; set; }
        public Nullable<byte> Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> IsMilesCard { get; set; }
        public string MilesCardNumber { get; set; }
        public string AirlineCode { get; set; }
        public Nullable<decimal> PaxGiaCoBan { get; set; }
        public Nullable<decimal> PaxTaxAndFee { get; set; }
        public Nullable<decimal> PaxAddOnFee { get; set; }
        public Nullable<decimal> PaxServiceFee { get; set; }
        public Nullable<decimal> PaxPrice { get; set; }
        public string PaxNote { get; set; }
        public Nullable<decimal> TaxAndFeeExcludeDiscount { get; set; }
        public Nullable<decimal> ServiceFee { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> Active { get; set; }
        public string EticketNumberOutBound { get; set; }
        public string EticketNumberInBound { get; set; }
        public string FullName { get; set; }
        public string PNROutBound { get; set; }
        public string PNRInBound { get; set; }
        public Nullable<int> OrderTourId { get; set; }
    }
}
