//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderReceipt
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderPaymentId { get; set; }
        public string Content { get; set; }
        public Nullable<int> UserIdPrint { get; set; }
        public Nullable<System.DateTime> DatePrint { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public string Office { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<byte> PaymentMethod { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public string ReasonCancel { get; set; }
        public Nullable<bool> IsBankDeposit { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
    }
}
