//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.TimeSpan> PaymentTime { get; set; }
        public Nullable<byte> PaymentMethod { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentNote { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<byte> PaymentStatus { get; set; }
        public Nullable<int> CreditCardFeeId { get; set; }
        public Nullable<decimal> FeePrice { get; set; }
        public Nullable<int> DeliveryUserId { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
    }
}
