//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRecheck
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<byte> PassengerName { get; set; }
        public Nullable<byte> FlightNumberOut { get; set; }
        public Nullable<byte> DepartureDateOut { get; set; }
        public Nullable<byte> FlightNumberIn { get; set; }
        public Nullable<byte> DepartureDateIn { get; set; }
        public Nullable<System.DateTime> DateTimeRecheck { get; set; }
    }
}
