//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFlight
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderCode { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> ProcessedBy { get; set; }
        public Nullable<byte> Triptype { get; set; }
        public string ItineraryDesc { get; set; }
        public Nullable<byte> PaymentMethod { get; set; }
        public Nullable<byte> TotalAdult { get; set; }
        public Nullable<byte> TotalChild { get; set; }
        public Nullable<byte> TotalInfant { get; set; }
        public Nullable<decimal> TotalBasePrice { get; set; }
        public Nullable<decimal> TotalTaxAndFee { get; set; }
        public Nullable<decimal> TotalAddOnFee { get; set; }
        public Nullable<decimal> TotalServiceFee { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string PriceNote { get; set; }
        public Nullable<byte> OptionGetBetterFare { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<byte> Supplier { get; set; }
        public Nullable<byte> KeepSeat15minStatus { get; set; }
        public string SessionIdGDS { get; set; }
        public Nullable<System.DateTime> DateTimeKeepSeat { get; set; }
        public string PnrFake { get; set; }
        public Nullable<byte> PnrKeepStatus { get; set; }
        public Nullable<System.DateTime> DateTimeCreatePnr { get; set; }
        public Nullable<bool> IsShowFlagSNB { get; set; }
        public Nullable<int> NoFlagSNB { get; set; }
        public Nullable<bool> IsShowFlagTML { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public string PNRNumber { get; set; }
        public Nullable<byte> Enviroment { get; set; }
        public Nullable<bool> IsRoundTrip { get; set; }
        public string DepartureAirport { get; set; }
        public string ArrivalAirport { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string DepartureCity { get; set; }
        public string ArrivalCity { get; set; }
        public Nullable<int> RecommendationNumber { get; set; }
        public string OutBoundRefNumber { get; set; }
        public string InBoundRefNumber { get; set; }
        public Nullable<byte> Adult { get; set; }
        public Nullable<byte> Child { get; set; }
        public Nullable<byte> Infant { get; set; }
        public Nullable<bool> IsIssuedEticket { get; set; }
        public string TicketClass { get; set; }
        public string AirlineCode { get; set; }
        public string AirlineCodeInBound { get; set; }
    }
}
