//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRemark
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> UserIdCreate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Url { get; set; }
        public Nullable<int> TodolistId { get; set; }
        public string Domain { get; set; }
    }
}
