//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransaction
    {
        public int Id { get; set; }
        public Nullable<int> RecordType { get; set; }
        public Nullable<int> TransactionStatus { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> ContentId { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<int> TransactionMethod { get; set; }
        public Nullable<int> InWhere { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<int> SendTo { get; set; }
        public Nullable<int> SendFrom { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> UserProcess { get; set; }
        public Nullable<int> UserApprove { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserLogin { get; set; }
        public Nullable<System.DateTime> DateTimeInsert { get; set; }
        public Nullable<System.DateTime> DateTimeUpdate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
