//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHotel
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int HotelId { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> TotalRoom { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string RuleOfRoom { get; set; }
        public string RuleOfSKT { get; set; }
        public string PassengerDetail { get; set; }
        public Nullable<int> TotalAdult { get; set; }
        public Nullable<int> TotalChild { get; set; }
        public Nullable<int> TotalInfant { get; set; }
    }
}
