//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBooking
    {
        public int OrderId { get; set; }
        public Nullable<byte> StatusAvailable { get; set; }
        public Nullable<byte> FinnalStatus { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<bool> IsHotel { get; set; }
        public Nullable<bool> IsFlight { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<bool> IsRequirePayment { get; set; }
        public Nullable<byte> PaymentMethodSelected { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<byte> SupplierHotel { get; set; }
        public Nullable<byte> SupplierFlight { get; set; }
        public Nullable<byte> OrderStep { get; set; }
        public string BookingReference { get; set; }
        public string OrderErrorMessage { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsShowFrontEnd { get; set; }
        public string IPAddress { get; set; }
        public string Domain { get; set; }
        public Nullable<decimal> PriceFirstPaid { get; set; }
        public Nullable<decimal> ExtraFee { get; set; }
        public Nullable<byte> ExtraFeeType { get; set; }
        public Nullable<byte> PaymentStatusFinnal { get; set; }
        public string UserCity { get; set; }
        public string UserCountry { get; set; }
        public Nullable<System.DateTime> LastTimeValidBankOrCashOrigin { get; set; }
        public Nullable<System.DateTime> LastTimeValidBankOrCashCurrent { get; set; }
        public Nullable<System.DateTime> LastTimeValidBank { get; set; }
        public Nullable<System.DateTime> LastTimeValidCash { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<bool> IsTracking { get; set; }
        public Nullable<bool> IsBooking { get; set; }
        public Nullable<int> UserIdProcess { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<byte> CallPaxStatus { get; set; }
        public Nullable<System.DateTime> CallPaxFromTime { get; set; }
        public Nullable<System.DateTime> CallPaxToTime { get; set; }
        public Nullable<int> CallPaxUser { get; set; }
        public Nullable<System.DateTime> DateTimeProcess { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<int> UserIdAssignedBooking { get; set; }
        public Nullable<byte> UserAssingedBookingStatus { get; set; }
        public Nullable<int> UserIdAssingedCallPax { get; set; }
        public Nullable<byte> UserAssingedCallPaxStatus { get; set; }
        public Nullable<bool> IsKeepSeat { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<int> KeepSeatByUserId { get; set; }
        public Nullable<System.DateTime> AssignedBookingDate { get; set; }
        public Nullable<System.DateTime> DateTimeKeepSeat { get; set; }
        public Nullable<System.DateTime> TimeLimit { get; set; }
        public Nullable<int> UserIdUpdateStatus { get; set; }
        public Nullable<bool> IsRecallPax { get; set; }
        public Nullable<bool> XiCangDan { get; set; }
        public Nullable<int> LogClientId { get; set; }
        public Nullable<System.DateTime> DateTimeClickPayment { get; set; }
        public Nullable<System.DateTime> DateTimeDelivery { get; set; }
        public Nullable<System.DateTime> DateTimeRecall { get; set; }
        public Nullable<int> UserRecall { get; set; }
        public Nullable<byte> StatusRecall { get; set; }
        public Nullable<System.DateTime> DateTimeDoneRecall { get; set; }
        public Nullable<int> UserIdDeactive { get; set; }
        public Nullable<System.DateTime> DateTimeDeactive { get; set; }
        public Nullable<bool> NeedToResell { get; set; }
        public Nullable<byte> InvoiceStatus { get; set; }
        public Nullable<int> UserInvoiceRequest { get; set; }
        public Nullable<int> UserInvoiceIssued { get; set; }
        public Nullable<System.DateTime> UserInvoiceRequestTime { get; set; }
        public Nullable<System.DateTime> UserInvoiceIssuedTime { get; set; }
        public Nullable<bool> NeedToBeIssued { get; set; }
        public Nullable<bool> Issued { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<byte> OriginOnlinePaymentStatus { get; set; }
        public Nullable<bool> Refunded { get; set; }
        public Nullable<bool> IsDebt { get; set; }
        public string DebtReason { get; set; }
        public Nullable<bool> NeedToSell { get; set; }
        public Nullable<bool> CanExploited { get; set; }
        public string PayAtBank { get; set; }
        public Nullable<bool> HasLoss { get; set; }
        public Nullable<decimal> LostAmount { get; set; }
        public Nullable<bool> HasSMSBank { get; set; }
        public Nullable<decimal> DepositAmmount { get; set; }
        public Nullable<byte> KeepSeatStatus { get; set; }
        public Nullable<byte> RemindBeforeFlyStatus { get; set; }
        public Nullable<byte> RemindBeforeFlyQuality { get; set; }
        public Nullable<byte> RemindBeforeFlyUser { get; set; }
        public Nullable<System.DateTime> RemindBeforeFlyCallDate { get; set; }
        public string DeactiveReason { get; set; }
        public Nullable<byte> DeactiveStatus { get; set; }
        public Nullable<bool> NeedToDelivery { get; set; }
        public string DeliveryAddess { get; set; }
        public Nullable<bool> Delivered { get; set; }
        public Nullable<bool> IsTour { get; set; }
        public Nullable<bool> IsBlockFlight { get; set; }
        public string VoucherCode { get; set; }
    }
}
