//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEmail
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string FromEmail { get; set; }
        public string FromName { get; set; }
        public string ToEmail { get; set; }
        public string EmailSubject { get; set; }
        public string EmailContent { get; set; }
        public Nullable<byte> EmailContentType { get; set; }
        public Nullable<int> UserIdLogin { get; set; }
        public Nullable<int> UserIdReceive { get; set; }
        public Nullable<System.DateTime> DateTimeSent { get; set; }
        public Nullable<bool> IsError { get; set; }
        public string Error { get; set; }
        public string PC { get; set; }
        public string Domain { get; set; }
    }
}
