//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBaggage
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderTravellerId { get; set; }
        public string AirlineOutBound { get; set; }
        public Nullable<decimal> PriceOutBound { get; set; }
        public Nullable<int> KgOutBound { get; set; }
        public string AirlineInBound { get; set; }
        public Nullable<decimal> PriceInBound { get; set; }
        public Nullable<int> KgInBound { get; set; }
    }
}
