//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFlightSegment
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderFlightId { get; set; }
        public string AirlineCode { get; set; }
        public Nullable<int> FlightNumber { get; set; }
        public string TicketClass { get; set; }
        public string TicketClassName { get; set; }
        public string DepartureAirport { get; set; }
        public string ArrivalAirport { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.TimeSpan> ArrivalTime { get; set; }
        public Nullable<decimal> SegmentPrice { get; set; }
        public string PNRNumber { get; set; }
        public string EticketNumber { get; set; }
        public Nullable<byte> PNRStatus { get; set; }
        public string Timelimit { get; set; }
        public Nullable<byte> SegmentType { get; set; }
        public Nullable<System.DateTime> TimeRemindCustomer { get; set; }
        public Nullable<byte> RemindCustomerStatus { get; set; }
        public Nullable<int> GroupIndex { get; set; }
        public string SI { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public string FareRule { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> PriceShownOnTicket { get; set; }
        public Nullable<byte> RecheckStatus { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> UserIdRecheck { get; set; }
        public string ARC_FullBookingDetail { get; set; }
        public Nullable<int> ARC_BookStatus { get; set; }
        public string ContentIssue { get; set; }
    }
}
