//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPaymentSoHa
    {
        public int Id { get; set; }
        public string Order_Id { get; set; }
        public string Order_Product_Title { get; set; }
        public string Transaction_Info { get; set; }
        public string Order_Code { get; set; }
        public string Order_Email { get; set; }
        public string Order_Session { get; set; }
        public string price { get; set; }
        public string Site_Code { get; set; }
        public string Response_Code { get; set; }
        public string Response_Message { get; set; }
        public string Payment_Type { get; set; }
        public Nullable<System.DateTime> Payment_Time { get; set; }
        public string Error_Text { get; set; }
        public Nullable<System.DateTime> DateTimeInsert { get; set; }
        public Nullable<System.DateTime> DateTimeResponse { get; set; }
        public string Response_Discription { get; set; }
        public string Secure_Code { get; set; }
        public string Response_Order_Id { get; set; }
    }
}
