//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchSession
    {
        public int Id { get; set; }
        public Nullable<byte> ServiceSearched { get; set; }
        public string PCName { get; set; }
        public string Domain { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> DateTimeInsert { get; set; }
    }
}
