//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchInput
    {
        public int Id { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<bool> IsRoundTrip { get; set; }
        public string DepartureAirport { get; set; }
        public string ArrivalAirport { get; set; }
        public string DepartureCity { get; set; }
        public string ArrivalCity { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> RequestMaxResult { get; set; }
        public Nullable<byte> AdultNumber { get; set; }
        public Nullable<byte> ChildNumber { get; set; }
        public Nullable<byte> InfantNumber { get; set; }
        public Nullable<byte> TotalPax { get; set; }
        public Nullable<System.DateTime> DateTimeInsert { get; set; }
        public Nullable<bool> IsSearchDomestic { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> SearchIndividual { get; set; }
        public string AirlineCode { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
