//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceFee
    {
        public int Id { get; set; }
        public Nullable<bool> IsDomestric { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<int> BeforeFlightDay { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
