//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSBank
    {
        public int Id { get; set; }
        public Nullable<byte> Type { get; set; }
        public string OrderId { get; set; }
        public string SMSContent { get; set; }
        public string BookingReference { get; set; }
        public string Ammount { get; set; }
        public Nullable<decimal> RealMoney { get; set; }
        public string Bank { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserIdPost { get; set; }
        public Nullable<int> UserIdRecieve { get; set; }
        public Nullable<int> UserIdUpdate { get; set; }
        public Nullable<bool> Expired { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
