//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickitBlockFlight
    {
        public int Id { get; set; }
        public string PrnNumber { get; set; }
        public string AirlineCode { get; set; }
        public string AirlineName { get; set; }
        public string FlightNumberOut { get; set; }
        public string FlightNumberIn { get; set; }
        public string TicketClassOut { get; set; }
        public string TicketClassNameOut { get; set; }
        public string TicketClassIn { get; set; }
        public string TicketClassNameIn { get; set; }
        public string DepartureAirport { get; set; }
        public string ArrivalAirport { get; set; }
        public Nullable<System.DateTime> DepartureDateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public Nullable<decimal> PriceAdult { get; set; }
        public Nullable<decimal> PriceSaleAdult { get; set; }
        public Nullable<decimal> PriceChild { get; set; }
        public Nullable<decimal> PriceSaleChild { get; set; }
        public Nullable<decimal> PriceInfant { get; set; }
        public Nullable<decimal> PriceSaleInfant { get; set; }
        public string ConditionsTickets { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateTimeEnd { get; set; }
        public Nullable<bool> IsRoundTrip { get; set; }
        public Nullable<bool> IsSearchDomestic { get; set; }
        public Nullable<int> CountTickit { get; set; }
        public Nullable<int> AlreadySold { get; set; }
        public Nullable<bool> IsHot { get; set; }
    }
}
