//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> City { get; set; }
        public string Summary { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Schedule { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<System.DateTime> ShowFromDate { get; set; }
        public Nullable<System.DateTime> ShowEndDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsDomestic { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string Title { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public string Url { get; set; }
        public Nullable<int> TourCategory { get; set; }
        public Nullable<int> OrderDisplay { get; set; }
    }
}
