//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnoverWage
    {
        public int Id { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<int> KeepSeatCount { get; set; }
        public Nullable<int> BookingProcessCount { get; set; }
    }
}
