//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketProtechGroup.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStaff
    {
        public int Id { get; set; }
        public string Office { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<byte> UserRole { get; set; }
        public string JobTitle { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Yahoo { get; set; }
        public string Skype { get; set; }
        public string Hotline { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsStaff { get; set; }
        public Nullable<bool> IsTicketing { get; set; }
        public Nullable<bool> AllowAccessAdmin { get; set; }
        public Nullable<bool> HideAdminMenu { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public Nullable<bool> IsShowNote { get; set; }
        public Nullable<int> OrderDisplay { get; set; }
        public Nullable<bool> IsDefaultOnline { get; set; }
        public Nullable<byte> FareType { get; set; }
        public Nullable<bool> OffWork { get; set; }
        public Nullable<int> HotlineStatus { get; set; }
    }
}
